### ISSUE TITLE
Faraday::ParsingError on all requests.

### ISSUE THREAD

**Issue by jbutton** [jpalumickas/mailerlite-ruby#20] opened 2020-06-29 12:49 UTC
Hello
Recently I've started to get this error on all gem methods, I've updated to newest gem version 1.10.0 and also tried to increase request timeout, but it's still the same response:

Faraday::ParsingError: 785: unexpected token at '<!DOCTYPE html> <html lang=en>   <meta charset=utf-8>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">   <title>Error 400 (Bad Request)!!1</title> 

Mailerlite API works when calling from CURL

**Comment by jpalumickas** [comment] 2020-06-29 13:44
@jbutton Thanks for informing! will check this later today or tomorrow!

**Comment by jpalumickas** [comment] 2020-06-29 15:03
@jbutton released v1.12.0 , can you check if this solves a problem for you?

**Comment by adonaldson** [comment] 2020-06-29 15:43
Hi all - I know that MailerLite were doing some major infrastructure upgrades this weekend and for me at least, the latest fix doesn't seem to work. 

I've dropped their team an email to see if they can provide a little more information in regards to what has changed / what we need to do to get requests running again.

**Comment by jpalumickas** [comment] 2020-06-29 15:45
@adonaldson can you provide which method you use? I tested with `groups` and `create_group` and they worked fine for me after these changes.

**Comment by adonaldson** [comment] 2020-06-29 15:51
hey @jpalumickas - I'm seeing the error on `groups` - weirdly, not on `create_group` (or `delete_group` when tidying up!). Let me dig into this, there's a good chance the problem is with me, not you!

**Comment by jpalumickas** [comment] 2020-06-29 15:53
@adonaldson can you double check if you use updated **v1.12.0** version?

**Comment by adonaldson** [comment] 2020-06-29 16:07
@jpalumickas hi - I can confirm the problem was wholly at my end. My apologies for the distraction! This looks to be working as you intended. Cheers!

**Comment by adonaldson** [comment] 2020-06-29 16:13
@jpalumickas not to take this too far off course, but how did you debug this one? I can't seem to get any feedback from the API calls beyond the 400 / Bad request. Short of you providing this fix I feel like I would have been doing a lot of trial and error!

Was there an update in the docs this weekend or an announcement I've missed?

**Comment by dominykasmailer** [comment] 2020-06-30 05:28
Hello everyone, I'm the lead developer here at Mailerlite :)

First of all I would like to say sorry for any inconveniences caused, we're working hard to make everything stable on our new infrastructure.

I can see that this will be caused by our new infrastructure and configs and it shouldn't be like this...

I will test the 1.10.0 version to see if I can reproduce it mysql and then we'll work on making it behave the same way like it was before so no more changes/testing is required to make the libraries behave the same way.

Stay tuned!

**Comment by dominykasmailer** [comment] 2020-06-30 06:32
Hello again, seems like Google Cloud does not accept incorrectly provided request body.

In this case groups and other GET method can't have any body. Looking at the code it was probably sending `{}` which can be easily reproducible here:

```bash
curl --location --request GET 'https://api.mailerlite.com/api/v2/groups' \
--header 'X-MailerLite-ApiKey: AAAA' \
--header 'Content-Type: application/json' \
--data-raw '{}'
``` 

We're not happy that we you needed to make a change to your library for it to work but there really shouldn't be any body in GET requests.

I have test 1.12.0 version and it does fix this issue. Looking at other community libraries there weren't any more cases like this

I hope I have helped you with this issue :)

**Comment by jpalumickas** [comment] 2020-06-30 08:46
@dominykasmailer thanks for clarification! so I guess I can close this issue then. 🙂 
Cheers

**Closed by jpalumickas** 2020-06-30 08:46 UTC
